# KorNLI Dataset

Data from Kakaobrain:  https://github.com/kakaobrain/KorNLUDatasets

In [22]:
import os
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

import numpy as np
import pandas as pd

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

import matplotlib.pyplot as plt

In [23]:
# 시각화

def plot_graphs(history, string):
    plt.plot(history.history[string])
    plt.plot(history.history['val_'+string], '')
    plt.xlabel("Epochs")
    plt.ylabel(string)
    plt.legend([string, 'val_'+string])
    plt.show()

In [24]:
#random seed 고정

tf.random.set_seed(1234)
np.random.seed(1234)

In [25]:
# BASE PARAM

BATCH_SIZE = 32
NUM_EPOCHS = 3
MAX_LEN = 48 
# 데이터 분석을 통해 도출한 최대 길이 24. 이 모델은 문장을 2개를 사용하기 때문에 *2해서 48을 사용

data_path = 'C:/nlp/tensorflow-ml-nlp-tf2/7.PRETRAIN_METHOD/data_in/KOR/KorNLI/'
op = "C:/nlp/tensorflow-ml-nlp-tf2/7.PRETRAIN_METHOD/data_out/"

In [26]:
train_snli_data = pd.read_csv(data_path + 'snli_1.0_train.kor.tsv', header = 0, delimiter = '\t', quoting =3)
train_xnli_data = pd.read_csv(data_path + 'multinli.train.ko.tsv', header = 0, delimiter = '\t', quoting =3)
dev_xnli_data = pd.read_csv(data_path + 'xnli.dev.ko.tsv', header = 0, delimiter = '\t', quoting =3)

In [27]:
train_data = train_snli_data.append(train_xnli_data)
train_data = train_data.dropna()
train_data = train_data.reset_index()

dev_xnli_data = dev_xnli_data.dropna()

# dropna 데이터의 소수 부분은 학습에 사용이 불가하기에 사용.

print(f"train_Data:{len(train_data)}, dev_data: {len(dev_xnli_data)}")

train_Data:942808, dev_data: 2490


In [40]:
train_data.head(10)

index                                          sentence1  \
0      0                         말을 탄 사람이 고장난 비행기 위로 뛰어오른다.   
1      1                         말을 탄 사람이 고장난 비행기 위로 뛰어오른다.   
2      2                         말을 탄 사람이 고장난 비행기 위로 뛰어오른다.   
3      3                                 카메라에 웃고 손을 흔드는 아이들   
4      4                                 카메라에 웃고 손을 흔드는 아이들   
5      5                                 카메라에 웃고 손을 흔드는 아이들   
6      6                 한 소년이 빨간 다리 한가운데 스케이트보드에 뛰어오르고 있다.   
7      7                 한 소년이 빨간 다리 한가운데 스케이트보드에 뛰어오르고 있다.   
8      8                 한 소년이 빨간 다리 한가운데 스케이트보드에 뛰어오르고 있다.   
9      9  나이 든 남자가 커피숍의 작은 테이블에 오렌지 주스를 들고 앉아 있고 밝은 색 셔츠...   

                          sentence2     gold_label  
0         한 사람이 경쟁을 위해 말을 훈련시키고 있다.        neutral  
1          한 사람이 식당에서 오믈렛을 주문하고 있다.  contradiction  
2                사람은 야외에서 말을 타고 있다.     entailment  
3                 그들은 부모님을 보고 웃고 있다        neutral  
4                           아이들이 있다     entailment  
5                  아이들이 얼굴을 찌푸리고 있다  contradiction  
6              소년은 인도를 따라 스케이트를 탄다.  contradiction  
7         그 소년은 스케이트보드를 타는 묘기를 부린다.     entailment  
8               소년이 안전 장비를 착용하고 있다.        neutral  
9  나이 든 남자가 딸이 퇴근하기를 기다리면서 주스를 마신다.        neutral

In [39]:
dev_xnli_data.head(10)

sentence1  \
0                           그리고 그가 말했다, "엄마, 저 왔어요."   
1                           그리고 그가 말했다, "엄마, 저 왔어요."   
2                           그리고 그가 말했다, "엄마, 저 왔어요."   
3  내가 무엇을 위해 가고 있는지 또는 어떤 것을 위해 있는지 몰랐기 때문에 워싱턴의 ...   
4  내가 무엇을 위해 가고 있는지 또는 어떤 것을 위해 있는지 몰랐기 때문에 워싱턴의 ...   
5  내가 무엇을 위해 가고 있는지 또는 어떤 것을 위해 있는지 몰랐기 때문에 워싱턴의 ...   
6                                        그는 갈 수 없었다.   
7                                        그는 갈 수 없었다.   
8                                        그는 갈 수 없었다.   
9                          그리고 저는 "괜찮아" 하고, 그게 다였어요!   

                                           sentence2     gold_label  
0                  그는 학교 버스가 그를 내려주자마자 엄마에게 전화를 걸었다.        neutral  
1                                    그는 한마디도 하지 않았다.  contradiction  
2                                그는 엄마에게 집에 갔다고 말했다.     entailment  
3  나는 워싱턴에 가본 적이 없어서 거기 배정을 받았을 때 그 장소를 찾으려다가 길을 ...        neutral  
4               워싱턴으로 진군하면서 해야 할 일이 무엇인지 정확히 알고 있었다.  contradiction  
5  나는 내가 무엇을 할 것인지 확신할 수 없어서 내가 보고를 하도록 배정받은 워싱턴으...     entailment  
6                       그는 처음 초대를 받은 사람이고 그 경험을 즐겼다.  contradiction  
7                               그는 참석하는 것을 허가받지 않았다.     entailment  
8                        그는 박물관 개관식에 가는 것이 허용되지 않았다.        neutral  
9                                내가 승낙한 후에, 그것은 끝났다.     entailment

In [28]:
# Bert Tokenizer

# 참조: https://huggingface.co/transformers/main_classes/tokenizer.html?highlight=encode_plus#transformers.PreTrainedTokenizer.encode_plus

tokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-cased", cache_dir='bert_ckpt', do_lower_case=False)

def bert_tokenizer_v2(sent1, sent2, MAX_LEN):
    
  # 텍스트 페어 옵션으로 학습할 데이터 만들어준다.
    
    encoded_dict = tokenizer.encode_plus(
        text = sent1,
        text_pair = sent2,
        add_special_tokens = True, # Add '[CLS]' and '[SEP]'
        max_length = MAX_LEN,           # Pad & truncate all sentences.
        pad_to_max_length = True,
        return_attention_mask = True   # Construct attn. masks.
        
    )
    
    input_id = encoded_dict['input_ids']
    attention_mask = encoded_dict['attention_mask'] # And its attention mask (simply differentiates padding from non-padding).
    token_type_id = encoded_dict['token_type_ids'] # differentiate two sentences
    
    return input_id, attention_mask, token_type_id

In [29]:
input_ids = []
attention_masks = []
token_type_ids = []

for sent1, sent2 in zip(train_data['sentence1'], train_data['sentence2']):
    
    try:
        input_id, attention_mask, token_type_id = bert_tokenizer_v2(sent1, sent2, MAX_LEN)

        input_ids.append(input_id)
        attention_masks.append(attention_mask)
        token_type_ids.append(token_type_id)
    except Exception as e:
        print(e)
        print(sent1, sent2)
        pass
    
train_snli_xnli_input_ids = np.array(input_ids, dtype=int)
train_snli_xnli_attention_masks = np.array(attention_masks, dtype=int)
train_snli_xnli_type_ids = np.array(token_type_ids, dtype=int)
train_snli_xnli_inputs = (train_snli_xnli_input_ids, train_snli_xnli_attention_masks, train_snli_xnli_type_ids)

In [56]:
print(train_snli_xnli_input_ids[2])
print(train_snli_xnli_attention_masks[2])
print(train_snli_xnli_type_ids[2])
print(tokenizer.decode(train_snli_xnli_input_ids[2]))
print(train_snli_xnli_inputs[2])

[  101  9251 10622  9847 97802  8888 13890 33305  9379 25549 12310  9619
 11261  9150 12965 28188 66346   119   102  9405 61250 10892  9538 78705
 11489  9251 10622  9845 11664 11506   119   102     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]
[CLS] 말을 탄 사람이 고장난 비행기 위로 뛰어오른다. [SEP] 사람은 야외에서 말을 타고 있다. [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 1 1]]


In [41]:
# 토크나이저를 제외하고는 5장에서 처리한 방식과 유사하게 접근
input_ids = []
attention_masks = []
token_type_ids = []

for sent1, sent2 in zip(dev_xnli_data['sentence1'], dev_xnli_data['sentence2']):
    try:
        input_id, attention_mask, token_type_id = bert_tokenizer_v2(sent1, sent2, MAX_LEN)

        input_ids.append(input_id)
        attention_masks.append(attention_mask)
        token_type_ids.append(token_type_id)
    except Exception as e:
        print(e)
        print(sent1, sent2)
        pass
    
dev_xnli_input_ids = np.array(input_ids, dtype=int)
dev_xnli_attention_masks = np.array(attention_masks, dtype=int)
dev_xnli_type_ids = np.array(token_type_ids, dtype=int)
dev_xnli_inputs = (dev_xnli_input_ids, dev_xnli_attention_masks, dev_xnli_type_ids)

In [45]:
# Label을 Netural, Contradiction, Entailment 에서 숫자 형으로 변경한다.
label_dict = {"entailment": 0, "contradiction": 1, "neutral": 2}
def convert_int(label):
    num_label = label_dict[label]    
    return num_label

train_data["gold_label_int"] = train_data["gold_label"].apply(convert_int)
train_data_labels = np.array(train_data['gold_label_int'], dtype=int)

dev_xnli_data["gold_label_int"] = dev_xnli_data["gold_label"].apply(convert_int)
dev_data_labels = np.array(dev_xnli_data['gold_label_int'], dtype=int)

print(f'train labels: {len(train_data_labels)}, dev labels: {len(dev_data_labels)}')


train labels: 942808, dev labels: 2490


In [46]:
class TFBertClassifier(tf.keras.Model):
    def __init__(self, model_name, dir_path, num_class):
        super(TFBertClassifier, self).__init__()

        self.bert = TFBertModel.from_pretrained(model_name, cache_dir=dir_path)
        self.dropout = tf.keras.layers.Dropout(self.bert.config.hidden_dropout_prob)
        self.classifier = tf.keras.layers.Dense(num_class, 
                                                kernel_initializer=tf.keras.initializers.TruncatedNormal(self.bert.config.initializer_range), 
                                                name="classifier")
        
    def call(self, inputs, attention_mask=None, token_type_ids=None, training=False):
        
        #outputs 값: # sequence_output, pooled_output, (hidden_states), (attentions)
        outputs = self.bert(inputs, attention_mask=attention_mask, token_type_ids=token_type_ids)
        pooled_output = outputs[1] 
        pooled_output = self.dropout(pooled_output, training=training)
        logits = self.classifier(pooled_output)

        return logits

cls_model = TFBertClassifier(model_name='bert-base-multilingual-cased',
                                  dir_path='bert_ckpt',
                                  num_class=3)

In [47]:
# 학습 준비하기
optimizer = tf.keras.optimizers.Adam(3e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
cls_model.compile(optimizer=optimizer, loss=loss, metrics=[metric])

In [48]:
#학습 진행하기
model_name = "tf2_KorNLI"

# overfitting을 막기 위한 ealrystop 추가
earlystop_callback = EarlyStopping(monitor='val_accuracy', min_delta=0.0001,patience=2)
checkpoint_path = os.path.join(DATA_OUT_PATH, model_name, 'weights.h5')
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create path if exists
if os.path.exists(checkpoint_dir):
    print("{} -- Folder already exists \n".format(checkpoint_dir))
else:
    os.makedirs(checkpoint_dir, exist_ok=True)
    print("{} -- Folder create complete \n".format(checkpoint_dir))
    
cp_callback = ModelCheckpoint(
    checkpoint_path, monitor='val_accuracy', verbose=1, save_best_only=True, save_weights_only=True)

# 학습과 eval 시작
history = cls_model.fit(train_snli_xnli_inputs, train_data_labels, epochs=NUM_EPOCHS,
            validation_data = (dev_xnli_inputs, dev_data_labels),
            batch_size=BATCH_SIZE, callbacks=[earlystop_callback, cp_callback])

#steps_for_epoch
print(history.history)

./data_out/KOR/KorNLI\tf2_KorNLI -- Folder create complete 

Epoch 1/3
  207/29463 [..............................] - ETA: 67:58:18 - loss: 0.9885 - accuracy: 0.4980

KeyboardInterrupt: 

# test data

In [51]:
test_data = pd.read_csv(data_path + 'xnli.test.ko.tsv', header=0, delimiter = '\t', quoting = 3)
test_data = test_data_xnli.dropna()
test_data.head()

sentence1  \
0  글쎄, 나는 그것에 관해 생각조차 하지 않았지만, 나는 너무 좌절했고, 결국 그에게...   
1  글쎄, 나는 그것에 관해 생각조차 하지 않았지만, 나는 너무 좌절했고, 결국 그에게...   
2  글쎄, 나는 그것에 관해 생각조차 하지 않았지만, 나는 너무 좌절했고, 결국 그에게...   
3  그리고 저는 그것이 특권이라고 생각했습니다, 그리고 여전히, 여전히, 당시 저는 A...   
4  그리고 저는 그것이 특권이라고 생각했습니다, 그리고 여전히, 여전히, 당시 저는 A...   

                                           sentence2     gold_label  
0                                나는 그와 다시 이야기하지 않았다.  contradiction  
1                나는 다시 그와 이야기를 하기 시작했다는 것에 너무 화가 났다.     entailment  
2                                    우리는 좋은 대화를 나눴다.        neutral  
3                    그날 현장에 나만 있었던 게 아니라는 걸 몰랐던 것이다.        neutral  
4  나는 AFFC 공군 경력 분야에서 그 번호를 가진 유일한 사람이라는 인상을 가지고 ...     entailment

In [52]:
# Test set도 똑같은 방법으로 구성한다.

input_ids = []
attention_masks = []
token_type_ids = []

for sent1, sent2 in zip(test_data['sentence1'], test_data['sentence2']):
    
    try:
        input_id, attention_mask, token_type_id = bert_tokenizer_v2(sent1, sent2, MAX_LEN)

        input_ids.append(input_id)
        attention_masks.append(attention_mask)
        token_type_ids.append(token_type_id)
    except Exception as e:
        print(e)
        print(sent1, sent2)
        pass
    
    
test_xnli_input_ids = np.array(input_ids, dtype=int)
test_xnli_attention_masks = np.array(attention_masks, dtype=int)
test_xnli_type_ids = np.array(token_type_ids, dtype=int)
test_xnli_inputs = (test_xnli_input_ids, test_xnli_attention_masks, test_xnli_type_ids)

In [55]:
test_data["gold_label_int"] = test_data["gold_label"].apply(convert_int)
test_data_xnli_labels = np.array(test_data['gold_label_int'], dtype=int)

print("# sents: {}, # labels: {}".format(len(test_xnli_input_ids), len(test_data_xnli_labels)))

# sents: 5010, # labels: 5010


In [54]:
results = cls_model.evaluate(test_xnli_inputs, test_data_xnli_labels, batch_size=512)
print("test loss, test acc: ", results)

# sents: 5010, # labels: 5010
